/**
 * Controller: Employee Management
 * Functionality: Handles creating new employee profiles (Create Operation).
 */

const db = require('../config/db');

// 1. Create New Employee Profile
exports.createEmployee = async (req, res) => {
    const { name, email, department } = req.body;

    // Basic Validation: Ensure no required fields are empty
    if (!name || !email || !department) {
        return res.status(400).json({ error: 'All fields (name, email, department) are required.' });
    }

    try {
        // Query to insert new employee into the database 
        const insertQuery = 'INSERT INTO employees (name, email, department) VALUES (?, ?, ?)';
        const [result] = await db.query(insertQuery, [name, email, department]);
        
        // Extract the auto-incremented ID generated by MySQL
        const newEmployeeId = result.insertId;

        // Send success response back to the client side
        res.status(201).json({
            message: 'Employee profile created successfully! 🎉',
            employeeId: newEmployeeId,
            data: { id: newEmployeeId, name, email, department }
        });
    } catch (error) {
        // Handle Duplicate Email Error (MySQL Error Code: ER_DUP_ENTRY)
        if (error.code === 'ER_DUP_ENTRY') {
            return res.status(400).json({ error: 'An employee with this email already exists.' });
        }
        console.error('Error creating employee:', error.message);
        res.status(500).json({ error: 'Internal Server Error', details: error.message });
    }
};

// 2. Fetch All Employees Profiles (Read Operation)
exports.getAllEmployees = async (req, res) => {
    try {
        // Query to get all records from employees table ordered by newest first
        const selectQuery = 'SELECT * FROM employees ORDER BY id DESC';
        const [rows] = await db.query(selectQuery);

        // Send the list of employees back to the client side
        res.status(200).json({
            message: 'Employees fetched successfully! 📋',
            count: rows.length,
            data: rows
        });
    } catch (error) {
        console.error('Error fetching employees:', error.message);
        res.status(500).json({ error: 'Internal Server Error', details: error.message });
    }
};

