/**
 * Controller: Employee Management
 * Functionality: Handles creating new employee profiles (Create Operation).
 */

const db = require('../config/db');

// 1. Create New Employee Profile
exports.createEmployee = async (req, res) => {
    const { name, email, department } = req.body;

    // Basic Validation: Ensure no required fields are empty
    if (!name || !email || !department) {
        return res.status(400).json({ error: 'All fields (name, email, department) are required.' });
    }

    try {
        // Query to insert new employee into the database 
        const insertQuery = 'INSERT INTO employees (name, email, department) VALUES (?, ?, ?)';
        const [result] = await db.query(insertQuery, [name, email, department]);
        
        // Extract the auto-incremented ID generated by MySQL
        const newEmployeeId = result.insertId;

        // Send success response back to the client side
        res.status(201).json({
            message: 'Employee profile created successfully! ',
            employeeId: newEmployeeId,
            data: { id: newEmployeeId, name, email, department }
        });
    } catch (error) {
        // Handle Duplicate Email Error (MySQL Error Code: ER_DUP_ENTRY)
        if (error.code === 'ER_DUP_ENTRY') {
            return res.status(400).json({ error: 'An employee with this email already exists.' });
        }
        console.error('Error creating employee:', error.message);
        res.status(500).json({ error: 'Internal Server Error', details: error.message });
    }
};

// 2. Fetch All Employees Profiles (Read Operation)
exports.getAllEmployees = async (req, res) => {
    try {
        // Query to get all records from employees table ordered by newest first
        const selectQuery = 'SELECT * FROM employees ORDER BY id DESC';
        const [rows] = await db.query(selectQuery);

        // Send the list of employees back to the client side
        res.status(200).json({
            message: 'Employees fetched successfully! ',
            count: rows.length,
            data: rows
        });
    } catch (error) {
        console.error('Error fetching employees:', error.message);
        res.status(500).json({ error: 'Internal Server Error', details: error.message });
    }
};

// 3. Fetch Single Employee Profile By ID (Read Operation)
exports.getEmployeeById = async (req, res) => {
    const { id } = req.params;

    try {
        // Query to locate a specific employee matching the provided ID
        const findQuery = 'SELECT * FROM employees WHERE id = ?';
        const [rows] = await db.query(findQuery, [id]);

        // Validation: If no matching record is returned from database
        if (rows.length === 0) {
            return res.status(404).json({ error: `Employee with ID ${id} not found.` });
        }

        // Send the found record back to the client side
        res.status(200).json({
            message: 'Employee record found!',
            data: rows[0]
        });
    } catch (error) {
        console.error('Error fetching employee by ID:', error.message);
        res.status(500).json({ error: 'Internal Server Error', details: error.message });
    }
};

// 4. Update Existing Employee Profile (Update Operation)
exports.updateEmployee = async (req, res) => {
    const { id } = req.params;
    const { name, email, department } = req.body;

    // Basic Validation: Ensure fields are not empty before firing SQL commands
    if (!name || !email || !department) {
        return res.status(400).json({ error: 'All fields (name, email, department) are required to execute updates.' });
    }

    try {
        // Query to modify matching data attributes dynamically using specific placeholder variables
        const updateQuery = 'UPDATE employees SET name = ?, email = ?, department = ? WHERE id = ?';
        const [result] = await db.query(updateQuery, [name, email, department, id]);

        // Check if rows Affected equals zero, meaning target employee profile ID does not exist
        if (result.affectedRows === 0) {
            return res.status(404).json({ error: `Cannot update profile. Employee with ID ${id} not found.` });
        }

        // Send confirmation back to client interface viewport environment
        res.status(200).json({
            message: 'Employee profile updated successfully!',
            data: { id, name, email, department }
        });
    } catch (error) {
        // Handle unique constraint conflict if the user changes email to an active alternative address
        if (error.code === 'ER_DUP_ENTRY') {
            return res.status(400).json({ error: 'Another active employee is already utilizing this corporate email address.' });
        }
        console.error('Error updating employee payload records:', error.message);
        res.status(500).json({ error: 'Internal Server Error instance fault encountered.', details: error.message });
    }
};

// 5. Delete Employee Profile By ID (Delete Operation)
exports.deleteEmployee = async (req, res) => {
    try {
        const { id } = req.params;
        await db.query('DELETE FROM employees WHERE id = ?', [id]);
        res.json({ message: "Employee record deleted successfully!" });
    } catch (error) {
        res.status(500).json({ error: "Failed to delete record." });
    }
};