/**
 * Controller: VFM Card Management
 * Functionality: Handles creating, reading, updating, and deleting corporate VFM cards (CRUD Operations).
 */

const db = require('../config/db');

// 1. Create New VFM Card Profile (Create Operation)
exports.createCard = async (req, res) => {
    const { employee_id, card_number, grocery_allowance, reward_points } = req.body;

    // Basic Validation: Ensure required fields are not empty
    if (!employee_id || !card_number) {
        return res.status(400).json({ error: 'Employee ID and Card Number are required.' });
    }

    try {
        // Handle default values if allowance or points are not provided in the request
        const allowance = grocery_allowance !== undefined ? grocery_allowance : 180.00;
        const points = reward_points !== undefined ? reward_points : 0;

        // Query to insert new VFM card into the database
        const insertQuery = 'INSERT INTO vfm_cards (employee_id, card_number, grocery_allowance, reward_points) VALUES (?, ?, ?, ?)';
        const [result] = await db.query(insertQuery, [employee_id, card_number, allowance, points]);
        
        // Extract the auto-incremented ID generated by MySQL
        const newCardId = result.insertId;

        // Send success response back to the client side
        res.status(201).json({
            message: 'VFM Card created successfully! ',
            cardId: newCardId,
            data: { id: newCardId, employee_id, card_number, grocery_allowance: allowance, reward_points: points }
        });
    } catch (error) {
        // Handle Duplicate Card Number Error (MySQL Error Code: ER_DUP_ENTRY)
        if (error.code === 'ER_DUP_ENTRY') {
            return res.status(400).json({ error: 'A VFM card with this card number already exists.' });
        }
        console.error('Error creating VFM card:', error.message);
        res.status(500).json({ error: 'Internal Server Error', details: error.message });
    }
};

// 2. Fetch All VFM Cards (Read Operation)
exports.getAllCards = async (req, res) => {
    try {
        // Query to get all cards along with employee details, ordered by newest first
        const selectQuery = `
            SELECT vfm_cards.*, employees.name, employees.department 
            FROM vfm_cards 
            JOIN employees ON vfm_cards.employee_id = employees.id 
            ORDER BY vfm_cards.id DESC
        `;
        const [rows] = await db.query(selectQuery);

        // Send the list of VFM cards back to the client side
        res.status(200).json({
            message: 'VFM Cards fetched successfully! ',
            count: rows.length,
            data: rows
        });
    } catch (error) {
        console.error('Error fetching VFM cards:', error.message);
        res.status(500).json({ error: 'Internal Server Error', details: error.message });
    }
};

// 3. Fetch Single VFM Card By ID (Read Operation)
exports.getCardById = async (req, res) => {
    const { id } = req.params;

    try {
        // Query to locate a specific card matching the provided ID with employee details
        const findQuery = `
            SELECT vfm_cards.*, employees.name, employees.department 
            FROM vfm_cards 
            JOIN employees ON vfm_cards.employee_id = employees.id 
            WHERE vfm_cards.id = ?
        `;
        const [rows] = await db.query(findQuery, [id]);

        // Validation: If no matching record is returned from database
        if (rows.length === 0) {
            return res.status(404).json({ error: `VFM Card with ID ${id} not found.` });
        }

        // Send the found record back to the client side
        res.status(200).json({
            message: 'VFM Card record found!',
            data: rows[0]
        });
    } catch (error) {
        console.error('Error fetching VFM card by ID:', error.message);
        res.status(500).json({ error: 'Internal Server Error', details: error.message });
    }
};

// 4. Update Existing VFM Card (Update Operation)
exports.updateCard = async (req, res) => {
    const { id } = req.params;
    const { grocery_allowance, reward_points } = req.body;

    // Basic Validation: Ensure fields are provided before firing SQL commands
    if (grocery_allowance === undefined || reward_points === undefined) {
        return res.status(400).json({ error: 'Grocery allowance and reward points are required to execute updates.' });
    }

    try {
        // Query to modify matching data attributes
        const updateQuery = 'UPDATE vfm_cards SET grocery_allowance = ?, reward_points = ? WHERE id = ?';
        const [result] = await db.query(updateQuery, [grocery_allowance, reward_points, id]);

        // Check if rows Affected equals zero, meaning target card ID does not exist
        if (result.affectedRows === 0) {
            return res.status(404).json({ error: `Cannot update card. VFM Card with ID ${id} not found.` });
        }

        // Send confirmation back to client interface
        res.status(200).json({
            message: 'VFM Card updated successfully!',
            data: { id, grocery_allowance, reward_points }
        });
    } catch (error) {
        console.error('Error updating VFM card records:', error.message);
        res.status(500).json({ error: 'Internal Server Error instance fault encountered.', details: error.message });
    }
};

// 5. Delete VFM Card By ID (Delete Operation)
exports.deleteCard = async (req, res) => {
    try {
        const { id } = req.params;
        const [result] = await db.query('DELETE FROM vfm_cards WHERE id = ?', [id]);
        
        // Validation to check if the record existed before deleting
        if (result.affectedRows === 0) {
            return res.status(404).json({ error: `Cannot delete. VFM Card with ID ${id} not found.` });
        }

        res.json({ message: "VFM Card record deleted successfully!" });
    } catch (error) {
        console.error('Error deleting VFM card:', error.message);
        res.status(500).json({ error: "Failed to delete record.", details: error.message });
    }
};